- name: Install PostgreSQL Repository
  ansible.builtin.dnf:
    name: dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    disable_gpg_check: true
